spring:
  application:
    name: hiddenpoint

  datasource:
    url: jdbc:mysql://localhost:3306/java_project
    username: root
    password: Qsh3181155
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html